### ISSUE TITLE
DELETE /trackings/:slug/:tracking_number

### ISSUE THREAD

**Issue by teddychan** [AfterShip/aftership-sdk-ios#3]
Please do it before this week.
### Question 2 - DELETE /trackings/:slug/:tracking_number

Cant delete tracking that has Required field like Shipping date.
Do you need that when delete?
If yes, please update in API. 

![screen shot 2014-11-27 at 10 04 22 am](https://cloud.githubusercontent.com/assets/1337797/5211434/0ff3a7a4-761d-11e4-9a95-84964bcb523b.png)
![740105995_14891781766350247353](https://cloud.githubusercontent.com/assets/1337797/5211441/74c6d46c-761d-11e4-8d3f-bae79d8e7335.jpg)

**Comment by rjuppa** [comment]
How did you solve it? I have the problem to delete tracking for deutsche post with python APIv4.
