### ISSUE TITLE
How to install SDK when i use AFNetworking '~>2.5.0'

### ISSUE THREAD

**Issue by MaximKotliar** [AfterShip/aftership-sdk-ios#9]
I've got a pod dependency error:
 [!] Unable to satisfy the following requirements:

- `AFNetworking (~> 2.5)` required by `Podfile`
- `AFNetworking (= 1.3.4)` required by `Podfile.lock`

**Comment by applesolutions** [comment]
What is status ???? 

Any solution ?

**Comment by kleung-aftership** [comment]
@applesolutions @MaximKotliar 
We have updated the SDK to version 1.1.9 to tackle the issue.

**Comment by applesolutions** [comment]
Hi there.

Thanks.

when we try to write the version 1.1.9 in the podfile, it gives the error
"[!] Unable to satisfy the following requirements:

- `Aftership-iOS-SDK (= 1.1.9)` required by `Podfile`"
And when we try to write without the version, it gives the same conflict
error as before.

"[!] Unable to satisfy the following requirements:

- `AFNetworking (= 2.6.2)` required by `Podfile`
- `AFNetworking (= 2.6.2)` required by `Podfile`
- `AFNetworking (= 2.6.2)` required by `Podfile`
- `AFNetworking (= 2.6.2)` required by `Podfile.lock`
- `AFNetworking (= 1.1.0)` required by `RestKit/Network (0.20.0)`"

Can you please confirm that the version 1.1.9 is available through pods?



Med Venlig hilsen / Kind regards

.
*Kundeservice*



*T:   +45 71 99 02 07 <%2B45%2071%2099%2002%2007>*
Mandag – Fredag: 14 – 16
Lørdag: Lukket
Søndag: Lukket
Http://AppleSolutions.dk



2016-10-12 4:41 GMT+02:00 kleung-aftership <notifications@github.com>:

**Comment by chiulam** [comment]
Sorry we have some problem publishing the version 1.1.9 to cocoapods.
Will fix it within these 2 days.

**Comment by chiulam** [comment]
Version 1.1.9 is available now

**Comment by applesolutions** [comment]
Hi there. 

Still not working :( 

https://www.dropbox.com/s/jnpqkqpo9svmiez/Screenshot%202016-10-22%2001.32.03.png?dl=0

**Comment by applesolutions** [comment]
Hi there.

We are still getting errors on it?

https://www.dropbox.com/s/jnpqkqpo9svmiez/Screenshot%202016-10-22%2001.32.03.png?dl=0



Med Venlig hilsen / Kind regards

.
*Kundeservice*



*T:   +45 71 99 02 07 <%2B45%2071%2099%2002%2007>*
Mandag – Fredag: 14 – 16
Lørdag: Lukket
Søndag: Lukket
Http://AppleSolutions.dk



2016-10-20 4:25 GMT+02:00 Chiu Lam <notifications@github.com>:
